// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:cofe': typeof import('~icons/uil/cofe')['default']
    'IconUil:coffe': typeof import('~icons/uil/coffe')['default']
    'IconUil:coffee': typeof import('~icons/uil/coffee')['default']
    'IconUil:coup': typeof import('~icons/uil/coup')['default']
    'IconUil:cup': typeof import('~icons/uil/cup')['default']
    'IconUil:fasHeart': typeof import('~icons/uil/fas-heart')['default']
    'IconUil:fbHeart': typeof import('~icons/uil/fb-heart')['default']
    'IconUil:filledHeart': typeof import('~icons/uil/filled-heart')['default']
    'IconUil:fillHeart': typeof import('~icons/uil/fill-heart')['default']
    'IconUil:hamburguer': typeof import('~icons/uil/hamburguer')['default']
    'IconUil:heart': typeof import('~icons/uil/heart')['default']
    'IconUil:heartStraight': typeof import('~icons/uil/heart-straight')['default']
    'IconUil:icBaselineAcUnit': typeof import('~icons/uil/ic-baseline-ac-unit')['default']
    'IconUil:lamp': typeof import('~icons/uil/lamp')['default']
    'IconUil:light': typeof import('~icons/uil/light')['default']
    'IconUil:lightbulb': typeof import('~icons/uil/lightbulb')['default']
    'IconUil:ligth': typeof import('~icons/uil/ligth')['default']
    'IconUil:linkedin': typeof import('~icons/uil/linkedin')['default']
    'IconUil:linkedinFill': typeof import('~icons/uil/linkedin-fill')['default']
    'IconUil:mamburguer': typeof import('~icons/uil/mamburguer')['default']
    'IconUil:menu': typeof import('~icons/uil/menu')['default']
    'IconUil:menuHamburguer': typeof import('~icons/uil/menu-hamburguer')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sepia': typeof import('~icons/uil/sepia')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:user': typeof import('~icons/uil/user')['default']
  }
}

export { }
