// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'IconUil:icBaselineAcUnit': typeof import('~icons/uil/ic-baseline-ac-unit')['default']
    'IconUil:linkedin': typeof import('~icons/uil/linkedin')['default']
    'IconUil:linkedinFill': typeof import('~icons/uil/linkedin-fill')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:user': typeof import('~icons/uil/user')['default']
  }
}

export { }
