// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'IconBxl:devTo': typeof import('~icons/bx/l-dev-to')['default']
    'IconMdi:devTo': typeof import('~icons/mdi/dev-to')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:brand': typeof import('~icons/uil/brand')['default']
    'IconUil:brandDev': typeof import('~icons/uil/brand-dev')['default']
    'IconUil:brandsDev': typeof import('~icons/uil/brands-dev')['default']
    'IconUil:brandsDevTo': typeof import('~icons/uil/brands-dev-to')['default']
    'IconUil:cofe': typeof import('~icons/uil/cofe')['default']
    'IconUil:coffe': typeof import('~icons/uil/coffe')['default']
    'IconUil:coffee': typeof import('~icons/uil/coffee')['default']
    'IconUil:coup': typeof import('~icons/uil/coup')['default']
    'IconUil:cup': typeof import('~icons/uil/cup')['default']
    'IconUil:dev': typeof import('~icons/uil/dev')['default']
    'IconUil:devBrand': typeof import('~icons/uil/dev-brand')['default']
    'IconUil:devto': typeof import('~icons/uil/devto')['default']
    'IconUil:devTo': typeof import('~icons/uil/dev-to')['default']
    'IconUil:faBrandsDev': typeof import('~icons/uil/fa-brands-dev')['default']
    'IconUil:fasHeart': typeof import('~icons/uil/fas-heart')['default']
    'IconUil:fbHeart': typeof import('~icons/uil/fb-heart')['default']
    'IconUil:filledHeart': typeof import('~icons/uil/filled-heart')['default']
    'IconUil:fillHeart': typeof import('~icons/uil/fill-heart')['default']
    'IconUil:github': typeof import('~icons/uil/github')['default']
    'IconUil:hamburguer': typeof import('~icons/uil/hamburguer')['default']
    'IconUil:hd': typeof import('~icons/uil/hd')['default']
    'IconUil:heart': typeof import('~icons/uil/heart')['default']
    'IconUil:heartStraight': typeof import('~icons/uil/heart-straight')['default']
    'IconUil:icBaselineAcUnit': typeof import('~icons/uil/ic-baseline-ac-unit')['default']
    'IconUil:instagram': typeof import('~icons/uil/instagram')['default']
    'IconUil:lamp': typeof import('~icons/uil/lamp')['default']
    'IconUil:light': typeof import('~icons/uil/light')['default']
    'IconUil:lightbulb': typeof import('~icons/uil/lightbulb')['default']
    'IconUil:ligth': typeof import('~icons/uil/ligth')['default']
    'IconUil:linkedin': typeof import('~icons/uil/linkedin')['default']
    'IconUil:linkedinFill': typeof import('~icons/uil/linkedin-fill')['default']
    'IconUil:logoDev': typeof import('~icons/uil/logo-dev')['default']
    'IconUil:mamburguer': typeof import('~icons/uil/mamburguer')['default']
    'IconUil:mdi:devTo': typeof import('~icons/uil/mdi-dev-to')['default']
    'IconUil:menu': typeof import('~icons/uil/menu')['default']
    'IconUil:menuHamburguer': typeof import('~icons/uil/menu-hamburguer')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sepia': typeof import('~icons/uil/sepia')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:user': typeof import('~icons/uil/user')['default']
    'IconUil:vuejs': typeof import('~icons/uil/vuejs')['default']
  }
}

export { }
